### ISSUE TITLE
Set background color to Transparent

### ISSUE THREAD

**Issue by GoogleCodeExporter** [oozcitak/imagelistview#175]
```
Hello guys,

How can i set background color of control to Transparent?

Any one can help me.

Best regard,
Peace
```

Original issue reported on code.google.com by `peacetra...@gmail.com` on 5 Jun 2015 at 11:11

**Comment by oozcitak** [comment]
This is not possible out of the box, but it could be done with a custom renderer by overriding [`DrawBackground`](https://github.com/oozcitak/imagelistview/blob/master/ImageListView/ImageListViewRenderer.cs#L953) and [`DrawItem`](https://github.com/oozcitak/imagelistview/blob/master/ImageListView/ImageListViewRenderer.cs#L1021).
