### ISSUE TITLE
Shared cache between several Image List Views

### ISSUE THREAD

**Issue by bladerx** [oozcitak/imagelistview#177]
Is there any easy way to share images between several list views?

If I have a main view which has all the images I want, and a secondary one that frequently adds and removes images that are always contained in this main view, can I add already cached images from the main view?

**Comment by oozcitak** [comment]
No, sorry, this is not possible.

**Comment by oozcitak** [comment]
There is the persistent cache feature not yet implemented though: https://github.com/oozcitak/imagelistview/blob/master/ImageListView/PersistentCache.cs

**Comment by bladerx** [comment]
Thanks for getting back to me.
