### ISSUE TITLE
Scroll bar issues

### ISSUE THREAD

**Issue by pc8181** [oozcitak/imagelistview#178]
keydown codes
           'ThumbnailSIze
       Try
            If e.KeyCode = Keys.Add OrElse e.KeyCode = Keys.Oemplus Then
                If ImgLsi.View = Manina.Windows.Forms.View.Thumbnails Then
                    If ImgLsi.ThumbnailSize.Width >= 500 Then Return
                    If ImgLsi.ThumbnailSize.Height >= 500 Then Return
                    ImgLsi.ThumbnailSize = New Size(ImgLsi.ThumbnailSize.Width + 10, ImgLsi.ThumbnailSize.Height + 10)
                    Return
                End If
            End If
        Catch ex As Exception
        Finally
            ImgLsi.ResumeLayout() : ImgLsi.Invalidate() : ImgLsi.Update() : ImgLsi.Refresh()
        End Try
![scroolbar issues](https://cloud.githubusercontent.com/assets/13380400/11390932/88392714-9374-11e5-8123-1346f7c5f4e7.jpg)

 without scrollbar nothing problem but suddenly showing the scrollbar some border lines showing with scrollbar.
i am using Invalidate and refresh method to the control but still the lines are showing how can hide this lines.

or 

just draw a selection like the picture near to scroll bar the lines are appear....but not gone

**Comment by pc8181** [comment]
wow !!! amazing fast fix ..

Thanks Sir :)

**Comment by oozcitak** [comment]
Thank you for the detailed information.
