### ISSUE TITLE
Nuget update 11.0.3 adds bitmap file to project

### ISSUE THREAD

**Issue by Jaex** [oozcitak/imagelistview#180]
When I updated from 11.0.1 to 11.0.3, QueuedBackgroundWorker.bmp file appeared in my project:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2016/01/SourceTree_dgSZTcOcI8.png)

But this bitmap file should be already exist in library so why it is also added to my project?

**Comment by oozcitak** [comment]
Thank you this should be fixed in the latest version. 

Fixed by 7262ad9ebc31ab3c9f78e9ecbb28b96327a6e0a7
