### ISSUE TITLE
Possible to supply my own drawing handlers?

### ISSUE THREAD

**Issue by UweKeim** [oozcitak/imagelistview#184]
Currently looking for a way to support SVG images in the ImageListView control.

My idea:
1. Provide a handler that gets called each time an image needs to be rendered.
2. In this handler, I get passed the image file path and the desired image dimensions.
3. I then load the SVG image into memory in my handler, render it with some 3rd-party SVG renderer to a bitmap.
4. Then, I return the in-memory bitmap from my handler back to ImageListView.
5. The ImageListView control uses my returned image instead of the image from the physical file location.

Is something like this possible?

**Comment by oozcitak** [comment]
Yes, you can use a custom `ImageListViewItemAdaptor` for this. Please take a look at the source code of [ImageListViewItemAdaptor](https://github.com/oozcitak/imagelistview/blob/master/ImageListView/ImageListViewItemAdaptor.cs) and the [two default adaptors](https://github.com/oozcitak/imagelistview/blob/master/ImageListView/ImageListViewItemAdaptors.cs).

**Comment by UweKeim** [comment]
Thanks a lot.
