### ISSUE TITLE
Exception in 11.0.4.0 but not in 11.0.0.0

### ISSUE THREAD

**Issue by pc8181** [oozcitak/imagelistview#186]
![errorimg](https://cloud.githubusercontent.com/assets/13380400/19838478/05fdb8da-9ef6-11e6-8bed-4e85668d4c94.jpg)

i added some psd files into this control i got lot of exception while loading every file
but the same time the older version like 11.0.0.0 working like charm did not get any
errors. 

i attached an image, i just add some psd(4 files) and jpg files control produces errors for psd files only not for jpg files

**Comment by oozcitak** [comment]
It looks like you do not have an imaging component for PSD files. Can you check that first please?

**Comment by pc8181** [comment]
just now .. after i installed adry codec and tested it i did not get any errors .. thank you so much sir..
but.. sorry for this question.. why i did not get any errors in 11.0.0.0 without any psd codec ?...
