### ISSUE TITLE
Image data pane view

### ISSUE THREAD

**Issue by fcazares** [oozcitak/imagelistview#189]
Hi

I'm loading images from a database into the imagelistview. Theres some data I want to show right next to the image so I thought I can use the pane view. But in the examples the information that the component shows is about an image file. Is there a way to load my information (maybe the Tag property) and show that information instead of the file information using the pane view?

**Comment by oozcitak** [comment]
You need to add a custom column to the `Columns` collection of the control and set values by calling `SetSubItemText`  of each `ImageListViewItem`. This will attach your custom data to the items. You can have as many custom columns as you need. However, the default pane renderer ignores data in custom columns. So you also need a custom renderer derived from `ImageListView.ImageListViewRenderer`. You just need to override the `DrawPane` virtual method and render your custom columns. You can probably modify the existing code to achieve this: https://github.com/oozcitak/imagelistview/blob/master/ImageListView/ImageListViewRenderers.cs#L991
