### ISSUE TITLE
Is it possible to find Drag/Drop options are succeeded or not ?

### ISSUE THREAD

**Issue by pc8181** [oozcitak/imagelistview#190]
Hi Sir :
   i have a little bit doubt, i am using Imagelistview control as an image browser into my form, sometimes i dropped image into an external editor from imagelistview control, worked fine. 
after image dropped then i want to modify items tag property in imagelistview so that how to
find Dropped image was successfully dropped done in Imagelistview. have any way to figure it out.

**Comment by oozcitak** [comment]
Are you dropping files into imagelistview? Or is it the other way around?

**Comment by pc8181** [comment]
i will add files into Imglsi with drag/drop or load files method. and every time i opened file into photoshop
via imaglistview drag/drop and item double click method. but i can change item tag property in item double click event but i could not changed in drag/drop methods.

![imglsv](https://cloud.githubusercontent.com/assets/13380400/24069778/7d54ef32-0bd6-11e7-996f-a7b54c25a6ae.jpg)

**Comment by pc8181** [comment]
Hi Sir,
  i tested 3 events today thanks for updating, but this 3 events raised only incoming objects into control
at the same how to capture file from Control to external dragging like outgoing ?... 
ex : drag files from control to Explorer

**Comment by fire-eggs** [comment]
Unless I misunderstand, you are asking if ImageListView can find out if a drag from the control can tell if a drop to an external target (e.g. Explorer) was "successful" or not.

As far as I'm aware, you are facing a limitation of Windows. Windows does not provide any mechanism to allow the drag _source_ to detect the results from a drop _target_.

When performing a drag-and-drop between applications, this is a data transfer between processes, similar to copy-and-paste via the clipboard. In both cases, the source merely provides the data, and has no information about the use of the data (or if the data was used at all). Using the clipboard example, if I use 'copy' to grab text from application A, said application has no idea where or if I use 'paste' to put the text into application B.
