### ISSUE TITLE
Double namespace when Nuget package is added

### ISSUE THREAD

**Issue by TinoMSoft** [oozcitak/imagelistview#191]
Hi

I added the nuget package 11.0.8 to my Windows Forms project, then are referenced a dll imagelistview.dll and imagelistview_nowpf.dll. Both libraries contains the class Manina.Windows.Forms.ImageListView. With this setup is it impossible to build the solution, when I reference the ImageListView class. Error is Ambiguous reference Manina.Windows.Forms.ImageListView.
After removing of one of the ImageListView dlls, can I compile.

Another problem is, I use signed dlls and a signed executable. For that I have to use a signed ImageListView dll or Nuget package. Is it possible to provide one?

Kind regards Tino

**Comment by oozcitak** [comment]
This should be fixed with the latest 11.1.0 release. The `UseWIC` property of the control now either dynamically loads an external WPF library for Windows Imaging functions or uses its native GDI+ image functions. There is no longer any need to publish to separate libraries.
