### ISSUE TITLE
Suggestion: Horizontal thumbnail mode and Show / hide image name option

### ISSUE THREAD

**Issue by d2phap** [oozcitak/imagelistview#193]
Hi!

Thanks for nice control!
I want to suggest the new 2 things:

## 1. Horizontal thumbnail mode (or just remove the main image of Gallery mode)
- This is useful to make thumbnail bar
![image](https://cloud.githubusercontent.com/assets/3154213/25008998/da1d4220-2097-11e7-9b3f-0343179b1db1.png)

## 2. Show / hide image name option
- Please add an option which allows user to hide the image name. When the thumbnail dimension is small (such as 48x48, 32x32,...) there are just a few characters displayed. It is unreadable and unnecessary to show.

----------
I also tried to customize the control but I don't know where to start.

Thanks a lot!

**Comment by pctweaks** [comment]
Here is a work around to add 48x48, 32x32 images.

Extract Image:
`   <DllImport("Shell32.dll", SetLastError:=False)>
    Public Shared Function SHDefExtractIcon(ByVal iconFile As String,
                                        ByVal iconIndex As Integer,
                                        ByVal flags As UInteger,
                                        ByRef hiconLarge As IntPtr,
                                        ByRef hiconSmall As IntPtr,
                                        ByVal iconSize As UInteger
) As Integer
    End Function` 

Usage:

`Usage:  SHDefExtractIcon(keyValue, 0, 0, hiconSmall, Nothing, 32)
Dim ico As Icon = Icon.FromHandle(hiconSmall)
Dim bmp As Bitmap = ico.ToBitmap()

Add images to ImageListview: ListView3.DefaultImage = bmp`

**Comment by pctweaks** [comment]
Also if you have a apply issue, you can do something like this.
References:------------------------------
`Dim valRunner As Integer`
` Dim Valoverlay As String`
 
Tool Strips:------------------------------

                 If X32ToolStripMenuItem.Checked Then
                    Dim hiconSmall As IntPtr
                    valRunner = 32
                    Valoverlay = hiconSmall
                End If

                If X48ToolStripMenuItem.Checked Then
                    Dim hiconSmall As IntPtr
                    valRunner = 48
                    Valoverlay = hiconSmall
                End If

                If X96ToolStripMenuItem.Checked Then
                    Dim hiconLarge As IntPtr
                    valRunner = 96
                    Valoverlay = hiconLarge
                End If

                If X120ToolStripMenuItem.Checked Then
                    Dim hiconLarge As IntPtr
                    valRunner = 120
                    Valoverlay = hiconLarge
                End If

                If X200ToolStripMenuItem.Checked Then
                    Dim hiconLarge As IntPtr
                    valRunner = 200
                    Valoverlay = hiconLarge
                End If

Usage:----------------------------------------------------------------
` SHDefExtractIcon(keyValue, 0, 0, Valoverlay, Nothing, valRunner)`
`Dim ico As Icon = Icon.FromHandle(Valoverlay)`
` Dim bmp As Bitmap = ico.ToBitmap()`

Add images to ImageListview: ListView3.DefaultImage = bmp

**Comment by oozcitak** [comment]
Added horizonral and vertical strip view modes with: 8711d17ca562c6bc618cdaba352014060d4a6bdb
