### ISSUE TITLE
How to get image from URL??

### ISSUE THREAD

**Issue by anhquoctran** [oozcitak/imagelistview#194]

**Comment by twobob** [comment]
roughly http://stackoverflow.com/questions/17876015/image-from-url-to-stream plus some coding

**Comment by oozcitak** [comment]
You can use the [`URIAdaptor`](https://github.com/oozcitak/imagelistview/blob/master/ImageListView/ImageListViewItemAdaptors.cs#L147).

**Comment by pc8181** [comment]
have any examples to download image direct to control via url ?

Thanks

**Comment by pc8181** [comment]
i'm create new uri adapter with link and then getthumbnail form uriadapter then add new item in listview but i got error in this line
`LsiImgOnline.Items.add(new ImagelistviewItem, "image", pbxadptrImage.image,_uriadapter)`

the error description is 
`Unable to cast object of type 'Manina.Windows.Forms.ImageListViewItem' to type 'System.String'.`


at the same time below code is working.. without error 👍 
``LsiImgOnline.Items.add(new ImagelistviewItem, pbxadptrImage.image,_uriadapter)``
