### ISSUE TITLE
How to get file name while drag and drop ?

### ISSUE THREAD

**Issue by pc8181** [oozcitak/imagelistview#195]
my form contains an ImgLsi and normal listview controls with properties (Imglsi.AllowDrop  = True,,
listview .AllowDrop  = True)

i m trying to add file name into Listview control from Imglsi drag and drop method m trying something
but i could not

in Listview  drag enter event caught string array (FileDrop,FileName, FileNameW) values
how to get file name value to add Listview

Thanks

**Comment by oozcitak** [comment]
ImageListView already supports drag&drop. It should accept image files dragged into it. For customizing the drop behavior, please see if the following events help:
- `DropFiles` - Fired after files are dropped into the control (external drag&drop)
- `DropItems` - Fired after items are rearranged in the control (internal drag&drop)
- `DropComplete` - Fired after drop operation (either internal or external) is completed and new items are added to the control.
