### ISSUE TITLE
Question: Thumbnails grayed-out in Demo

### ISSUE THREAD

**Issue by TimMakins** [oozcitak/imagelistview#196]
I downloaded the latest code, loaded the Solution into VS2015, and set the ImageListViewDemo as the Startup Project. When I run it, and view a folder of images, a number of the thumbnail-surrounds are grayed out, and when I click on those thumbnails, no information is displayed in the propertyGrid1. Why is this happening, please?

**Comment by TimMakins** [comment]
![image1](https://user-images.githubusercontent.com/11852571/31332741-7b941b64-acdf-11e7-8814-587eb9269e83.jpg)

**Comment by pc8181** [comment]
these items are disabled items, this will help to difference between enabled and disabled items

**Comment by TimMakins** [comment]
Sorry - I don't understand. What do you mean 'disabled'? How and why are they disabled? I don't see any difference in the File Attributes - they are all exactly the same for these images.

**Comment by oozcitak** [comment]
This is just a demo application. It demoes the visual state of disabled and enabled items. It doesn't have any other meaning.

**Comment by TimMakins** [comment]
OK, I understand that now. So where in the code are the items disabled? I can't spot it so far!

**Comment by TimMakins** [comment]
OH, I guess it must be:
`                    imageListView1.Items.Add(p.FullName);
                    if (i == 1) imageListView1.Items[imageListView1.Items.Count - 1].Enabled = false;
                    i++;
                    if (i == 3) i = 0;`
