### ISSUE TITLE
Can I Add bitmap to ImageListView?

### ISSUE THREAD

**Issue by Sixerito** [oozcitak/imagelistview#198]
Hi, I don't have filename on my c# object. Only Bitmap. I want/need add directly bitmap to ImageListView.

It is possible? 
Thx

**Comment by oozcitak** [comment]
Yes, use either of these overloads of the Add method of the item collection:
``` csharp
Add(ImageListViewItem item, Image initialThumbnail);
Add(string filename, Image initialThumbnail);
```
