### ISSUE TITLE
Cannot display thumbnails 

### ISSUE THREAD

**Issue by raphson93** [oozcitak/imagelistview#200]
* **I'm submitting a ...**
  - [ ] support request

* **What is the current behavior?**
when i load the file from remote server, it cannot display the image thumbnails

* **What is the expected behavior?**
we should be able to see the thumbnails

**Comment by oozcitak** [comment]
How do you fetch the remote images?

**Comment by raphson93** [comment]
> using (new Impersonation(networkDomain, networkUser, networkPassword))
            {
                var path = new DirectoryInfo(batchPath);
                //ActiveBatch = BatchPath;
                ThumbnailLists.Items.Clear();
                ThumbnailLists.SuspendLayout();
                FileInfo[] fileInfos = path.GetFiles("*.*");
                int count = 0;
                foreach (FileInfo p in fileInfos)
                {
                    if (p.Name.EndsWith(".jpg", StringComparison.OrdinalIgnoreCase) ||
                        p.Name.EndsWith(".png", StringComparison.OrdinalIgnoreCase) ||
                        p.Name.EndsWith(".bmp", StringComparison.OrdinalIgnoreCase) ||
                        p.Name.EndsWith(".ico", StringComparison.OrdinalIgnoreCase) ||
                        p.Name.EndsWith(".cur", StringComparison.OrdinalIgnoreCase) ||
                        p.Name.EndsWith(".emf", StringComparison.OrdinalIgnoreCase) ||
                        p.Name.EndsWith(".wmf", StringComparison.OrdinalIgnoreCase) ||
                        p.Name.EndsWith(".tif", StringComparison.OrdinalIgnoreCase) ||
                        p.Name.EndsWith(".tiff", StringComparison.OrdinalIgnoreCase) ||
                        p.Name.EndsWith(".gif", StringComparison.OrdinalIgnoreCase))
                    {
                        ThumbnailLists.Items.Add(p.FullName);
                        count++;
                    }
                }

                ThumbnailLists.ResumeLayout();


                if (count > 0)
                {
                    NumberPageBox.Text = count.ToString();
                }

                if (ThumbnailLists.Items.Count > 0)
                {
                    ImageListViewItem item = ThumbnailLists.Items[0];
                    Image img = Image.FromFile(item.FileName);
                    
                    if (ImageBox.Image != null)
                    {
                        ImageBox.Image.Dispose();
                    }

                    ImageBox.Image = img;
                    ImageBox.Focus();
                }
                else
                {
                    if (ImageBox.Image != null)
                    {
                        ImageBox.Image.Dispose();
                    }
                }

                CurrentPageBox.Text = "1";
            }

This is code i used to load the thumbnail from remote server (access via ip)

**Comment by oozcitak** [comment]
Is the image displayed in your `ImageBox`? I assume it is a picturebox control.

**Comment by raphson93** [comment]
hi, @oozcitak from the code above the image is displayed in imagebox

**Comment by oozcitak** [comment]
I made a small test by fetching a number of image files over a network share and it worked, though it was quite slow. I first thought your issue might be related to file system permissions. However since you are able to load files into a picturebox it must be something else. Does the image thumbnails show error icons? Can you test by adding a single file from the remote server using a hardcoded path?

**Comment by raphson93** [comment]
![image](https://user-images.githubusercontent.com/19220265/39236798-4fbfa666-48ac-11e8-99d5-fcbe9643d811.png)

@oozcitak this is what i got. not sure is this consider error icon

**Comment by oozcitak** [comment]
Can you try again by setting: 
```cs
     ThumbnailLists.UseWIC = false;
```
in your form's constructor.

**Comment by raphson93** [comment]
hi

i used `ThumbnailLists.UseWIC = 0;` instead still no luck

**Comment by oozcitak** [comment]
Please see if the latest 13.3 release solves this.
