### ISSUE TITLE
New Version Not Displaying PSD Thumbnail Through PSD Codec

### ISSUE THREAD

**Issue by shashisoftware** [oozcitak/imagelistview#201]
* **I'm submitting a ...**
  - [x] bug report

**Hello sir,** first of all i'll say you done a great job for ImageListView
few days ago i having a problem while using ImageListView.dll Verison 11.0.8
whenever i load some Nikon Model Camera 300DPI Picture, my programs getting hang in 64bit and getting exit in 32bit but now this issue completely gone in ImageListView.dll Verison 11.1.0 and now it's working fine with all camera photo, but now what happening **before when i was using ImageListView.dll Verison 11.0.8 then it was supporting and showing PSD Thumb if i'm using PSD Codec App in our system but now it's not working ImageListView not displaying Thumbnail of PSD however i'm using PSD Codec**
then i try with the old version of ImageListView.dll v11.0.8  then it's again start displaying PSD Thumbs
but i can't use this version of ImageListView.dll because as i already mention above i getting hanging problem with Nikon camera in this version, so please help me i will be very thankful of you.

**and please if any possibility to add any option to display PSD thumbs without using PSD Codec then it'll be useful for everyone because PSD Codec it's a paid program, so please consider adding PSD support.**

> And I'm Programming in VB.Net (Visual Basic)

Thank you.

**Comment by oozcitak** [comment]
Merging with #197.
