### ISSUE TITLE
Grouping items not only by first letter

### ISSUE THREAD

**Issue by Chatfix** [oozcitak/imagelistview#205]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request

* **What is the current behavior?**
Grouping items with GroupColumn and GroupOrder groups items only by first character. 

* **What is the expected behavior?**

Grouping items by full content of a column. 

* **If you are submitting a feature request, what is the motivation / use case for changing the behavior?**

Example grouping by foldername:
++P
Party Saturday - File 1
Party Saturday - File 2
Party Friday - File 1
Party Friday - File 2

The grouping in this case is useless. Better:

++Party Saturday
Party Saturday - File 1
Party Saturday - File 2
++Party Friday
Party Friday - File 1
Party Friday - File 2

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, etc)

Maybe its possible to add custom groups like the normal Listview Control

Thanks a lot for your great control!

**Comment by oozcitak** [comment]
I just added a `Grouper` property to column headers which should be an implementation of `ImageListView.IGrouper`. For example:

```cs
private class MyGrouper : ImageListView.IGrouper
{
    public ImageListView.GroupInfo GetGroupInfo(ImageListViewItem item)
    {
        string str = item.Text;
        while (str.Length < 3) str = "_" + str;
        str = str.Substring(0, 3);

        int hash = 0;
        int order = hash ^ str[0] ^ str[1] ^ str[2];

        return new ImageListView.GroupInfo(str, hash);
    }
}
```

and used like:
```cs
myImageListView.Columns[0].Grouper = new MyGrouper();
```
