### ISSUE TITLE
'System.ComponentModel.InvalidAsynchronousStateException' 

### ISSUE THREAD

**Issue by pc8181** [oozcitak/imagelistview#207]
Hi Sir, 
     Imagelistview is main control to my application but i got some errors always like below how to resolve this ?.. please help .....
 
  `Exception thrown: 'System.ComponentModel.InvalidAsynchronousStateException' in System.Windows.Forms.dll`

![image](https://user-images.githubusercontent.com/13380400/49690630-2e775100-fb5a-11e8-991d-96c25f0b8df6.png)

**Comment by oozcitak** [comment]
Aren't you using the library from nuget? Your screenshot shows VB code.

**Comment by pc8181** [comment]
application using .dll  and it did not get any issues,
but i tried to convert from c# to vb.net i got this error always i have no idea how to resolve this

**Comment by oozcitak** [comment]
Why don't you use the dll?

**Comment by oozcitak** [comment]
I advise you to use the DLL. You can always inherit from `ImageListView.ImageListViewRenderer`.

**Comment by pc8181** [comment]
k sir thanks, i will manage it :) ... have any idea about why those error occurred ?

**Comment by oozcitak** [comment]
Sorry, no.

**Comment by pc8181** [comment]
can provide a custom control or panel container added in an imagelistivew item like Checkbox and FileIcon ? it's really very helpful to all who is using ImageListView control because we can add some custom features in an individual items

Thanks.

**Comment by oozcitak** [comment]
Items are only visual representations. They are not actual controls. So they cannot house other controls. 

However, you can write a renderer and override the `DrawSubItemItemOverlay` method, which allows you to paint over the sub-items in details view mode. You could draw each button as a sub-item overlay then in the `ItemClick` event perform a hit test by using the `HitTest` method of the control to see if any buttons were clicked. 

Simple buttons or checkboxes can be mimicked by this method. But dropdown menus would be much harder. If you need such interaction with items I would advise you to consider [ObjectListView](http://objectlistview.sourceforge.net/cs/index.html).
