### ISSUE TITLE
Auto Clear Items

### ISSUE THREAD

**Issue by pc8181** [oozcitak/imagelistview#210]
Hi Sir,
            after  select some items in imagelistview control then select any other control in the form so i lost focus with some selected items in imagelistview, again mouse enter the control then click any item or any one selected item or control background then automatically all selected items were cleared is that normal behavior ?....have any way to maintain the selected items continuously  ?... 

Note*
but only one solution i can find out just select any one unselected item with control + shift key then all selected items is available otherwise not

and how to remove border in items like border less item in custom renderer (DrawItem overrides...)

**Comment by oozcitak** [comment]
This is normal behavior. Standard listviews work that way too. However, you can easily change this by deriving from `ImageListView` and overriding the mouse events.

To remove the border, you will need to create a custom renderer and override `DrawItem` as you said.

**Comment by pc8181** [comment]
thanks for your reply sir 
i tried my custom renderer and override Drawitem but i could not hide the border can you help me

![image](https://user-images.githubusercontent.com/13380400/53340039-006e0580-392e-11e9-821a-b37ab88f9642.png)

**Comment by oozcitak** [comment]
Can you post the source code of your draw item method?

**Comment by pc8181** [comment]
`
            _lsi.View = Manina.Windows.Forms.View.Thumbnails
            _lsi.SetRenderer(New ItemColorChanged)
            _lsi.Colors = Manina.Windows.Forms.ImageListViewColor.Noir
            _lsi.Colors.BorderColor = Color.Transparent
            _lsi.Colors.BackColor = Color.FromArgb(255, 51, 51, 51)

            _lsi.Colors.SelectedColor1 = Color.FromArgb(255, 0, 190, 255)
            _lsi.Colors.SelectedColor2 = Color.FromArgb(255, 0, 100, 255)


            _lsi.Colors.HoverBorderColor = Color.FromArgb(255, 255, 175, 0)
            _lsi.Colors.HoverColor1 = Color.FromArgb(255, 255, 0, 255)
            ' _lsi.Colors.HoverColor2 = Color.FromArgb(255, 255, 10, 0)


            _lsi.Colors.UnFocusedColor1 = Color.FromArgb(255, 0, 100, 0)
            _lsi.Colors.UnFocusedColor2 = Color.FromArgb(255, 0, 40, 0)


            _lsi.Colors.ImageInnerBorderColor = Color.FromArgb(255, 255, 255, 255)
            _lsi.Colors.ImageOuterBorderColor = Color.FromArgb(255, 0, 0, 255)

            _lsi.ThumbnailSize = _thumbSize
            _lsi.BorderStyle = BorderStyle.None
`

**Comment by oozcitak** [comment]
This line: `MyBase.DrawItem(g, item, state, bounds)` draws the border together with item background, image and text. You can either remove the line and draw item background and image yourself, or you can try drawing over the border with the background color.

**Comment by pc8181** [comment]
thank you so much finally i got it ...

 >      _lsi.Colors.ControlBackColor = Color.FromArgb(255, 51, 51, 51)
