### ISSUE TITLE
Multiple ImageListViews on Same Form

### ISSUE THREAD

**Issue by ab-tools** [oozcitak/imagelistview#215]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request

* **What is the current behavior?**
When there is more than one ImageListView on the same form displaying thumbnails does not work correctly (reloading thumbnails all the time (flickering) and displaying them in wrong size).

* **What is the expected behavior?**
You can have multiple ImageListView on the same form without problems (like any other Windows Forms control, too).

* **If you are submitting a bug report, please provide the steps to reproduce**
Just test with attached example project with two ImageListViews on one form:
[ImageListViewTest.zip](https://github.com/oozcitak/imagelistview/files/3855428/ImageListViewTest.zip)

Thanks in advance for your support!

**Comment by fire-eggs** [comment]
It's unfortunate, but the `ImageListViewItem` is tied to its "owning" `ImageListView`. In your project, you take the selected `ImageListViewItem` from the first view and add them to the second view; you now have two views trying to cache / track / render the thumbnails, and thus the flickering / wrong size issues.

What you need to do is break the view connection for the items, before adding them to the second view. The following change to your `imageListView1_SelectionChanged` method did the trick for me:
```
                imageListView2.Items.Add(selectedItem.Clone() as ImageListViewItem);
```
As a result, the two views now have separate copies of the `ImageListViewItem`, and each view can now render/cache as desired.

Seems kinda clunky, I know, but the "view association" seems to be fundamental to the control architecture and rather difficult to redesign.

**Comment by ab-tools** [comment]
I can confirm this works very well as you suggested and your explanation makes absolute sense, too.

Thanks a lot, appreciating your really quick reply!

Best regards
Andreas
