### ISSUE TITLE
How to visualize the top bar?

### ISSUE THREAD

**Issue by zboyanov** [oozcitak/imagelistview#217]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] support request

* **What is the expected behavior?**
How can I enable the top bar that controls the Renderer?
When I set the view to Details I don't get anything shown at the top.

**Comment by oozcitak** [comment]
Did you add columns?

**Comment by pc8181** [comment]
try this
 
`                              If ImgLsi.Columns.Count <= 0 Then
                                                 ImgLsi.Columns.Add(Manina.Windows.Forms.ColumnType.FileName)
                                   End If
                               ImgLsi.View = Manina.Windows.Forms.View.Details`

**Comment by zboyanov** [comment]
Zero columns and still not showing.
