### ISSUE TITLE
Drag and drop related problem

### ISSUE THREAD

**Issue by Jaex** [oozcitak/imagelistview#219]
Previously in ImageListView control I had `AllowDrag = true` and `AllowDrop = false` options set. It was allowing dragging files to explorer yet not allowing dragging files from explorer to control back. But few months ago I updated ImageListView library and noticed that thumbnails become re orderable and possible to drag items from explorer to control by default. So I disabled both "AllowDrop" and "AllowItemReorder" options and released our app. But then now I noticed "AllowDrop" option also affects dragging files from control to explorer. But if I re enable it then users also can drag files from explorer to control. So I thought I could just do:

```
        private void ilvImages_DragEnter(object sender, DragEventArgs e)
        {
            e.Effect = DragDropEffects.None;
        }
```

to not let dropping files to control, yet still it allows.

So I'm not sure how to let dragging files to explorer but not vice versa, like how it was working previously. I think solution to this problem should be is separating drag and drop logic, that way I can disable drop (explorer to control) and only allow drag (control to explorer).

**Comment by oozcitak** [comment]
I believe I got it right this time: I added back the `AllowDrag` property. Item reordering and drag&drop are separated from each other (with a small caveat).

| AllowDrag | AllowDrop | AllowItemReorder | Result |
|---|--------------------------|--------------------|------|
| `false` | `false` | `false` | No drag&drop; no item ordering |
| `false` | `false` | `true` | No drag&drop; item ordering allowed |
| `true` | `false` | `false` | Items can be dragged out onto external applications, but items cannot be dropped into control; no item ordering |
| `true` | `false` | `true` | Items can be dragged out onto external applications, but items cannot be dropped into control; no item ordering |
| `false` | `true` | `false` | Items can be dropped into control from external applications, but items cannot be dragged out from the control; no item ordering |
| `false` | `true` | `true` | Items can be dropped into control from external applications, but items cannot be dragged out from the control; dropped items can be inserted into where the caret points, which may result in item reordering |
| `true` | `true` | `false` | Items can be dropped into control from external applications, and they can be dragged out from the control; no item ordering |
| `true` | `true` | `true` | Items can be dropped into control from external applications, and they can be dragged out from the control; dropped items can be inserted into where the caret points, which may result in item reordering |
