### ISSUE TITLE
Problem with group column

### ISSUE THREAD

**Issue by eXclusif20** [oozcitak/imagelistview#220]
Hi,

Sorry for my english, i'm french and it's difficult for me. 
I am not a developer but I am trying to write an application (VB.NET Fx4.8) to improve document management as part of my work.

When I use the following properties to group items on their filepath

Me.imgLvwDocuments.GroupColumn = 4
Me.imgLvwDocuments.GroupOrder = SortOrder.AscendingNatural

I get a grouping but only on the first character of the filepath and not on the complete filepath.
Same result when I try to group it on the file type.

![image](https://user-images.githubusercontent.com/62645153/77524746-2b57bf80-6e88-11ea-92c2-cfd64e176adb.png)

I tried to understand the following code in C # to convert it to VBNET but I can't.

      private void GroupByCustom_Click(object sender, EventArgs e)
        {
            if (imageListView.Columns[0].Grouper == null)
            {
                imageListView.Columns[0].Grouper = new CustomGrouper();

                imageListView.GroupOrder = Manina.Windows.Forms.SortOrder.Ascending;
                imageListView.GroupColumn = 0;
                imageListView.SortColumn = 0;
                imageListView.SortOrder = Manina.Windows.Forms.SortOrder.Ascending;
            }
            else
            {
                imageListView.Columns[0].Grouper = null;

                imageListView.GroupOrder = Manina.Windows.Forms.SortOrder.None;
                imageListView.GroupColumn = 0;
                imageListView.SortColumn = 0;
                imageListView.SortOrder = Manina.Windows.Forms.SortOrder.None;
            }
        }

        private class CustomGrouper : ImageListView.IGrouper
        {
            public ImageListView.GroupInfo GetGroupInfo(ImageListViewItem item)
            {
                string str = item.Text;
                while (str.Length < 3) str = "_" + str;
                str = str.Substring(0, 3);

                int hash = 0;
                int order = hash ^ str[0] ^ str[1] ^ str[2];

                return new ImageListView.GroupInfo(str, hash);
            }
        }

This function is essential in my use. Do you think it is possible to add as standard a grouping taking into account the complete value and not only the first character?

Thank you in advance for your help, and above all thank you for providing such a practical and essential component.

* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [X] support request

* **What is the current behavior?**

Only the first character is user to group column

* **What is the expected behavior?**

All Characters of the value in column is used to group column

**Comment by oozcitak** [comment]
I just tested with a few images and sorting seems to be fine. It seems to be fine in your screenshot as well. Can you please show where you think sorting fails?

**Comment by eXclusif20** [comment]
Hi,


Thank you for your prompt response.

This is my case. I want to group the items on the file type (column 4).

So I added the commands to my code:

Me.imgLvwDocuments.GroupColumn = 4
Me.imgLvwDocuments.GroupOrder = SortOrder.AscendingNatural

Instead of having 3 groups in total. A first group named "JPG file", a second group named "TIFF file" and a third group named "Luminar 2018 ProdID".

![group column](https://user-images.githubusercontent.com/62645153/77648586-ae504700-6f68-11ea-97e1-eca9a7fedae2.png)

I get a first group named "F" (see 1) which contains the JPG and TIFF files and a second group called "L" (see 2) which contains the Luminar 2018 ProgID files.

Same problem when I try to group on column 5. I find myself with only one group named "C" which is the first character of the paths.

![group column path](https://user-images.githubusercontent.com/62645153/77648712-dfc91280-6f68-11ea-9d8b-a9e390da146b.png)

Am I doing something wrong?
Maybe this is normal operation?

Thanks for your help,

**Comment by oozcitak** [comment]
By default, groups from string columns only take into account the first letter of each item. The way custom grouping works is that you supply a group name to the control along with a hash code with that group, so all items with the same hash code will be grouped under that group name. If you want the control to group by the entire text you can create a custom group like this:
```csharp
private class CustomGrouper : ImageListView.IGrouper
{
    public ImageListView.GroupInfo GetGroupInfo(ImageListViewItem item)
    {
        string str = item.FilePath;
        return new ImageListView.GroupInfo(str, str.GetHashCode());
    }
}
```
The above group calculates the hash code from the entire file path of each item. You can assign to the control for example in your form's constructor:
```csharp
public DemoForm()
{
    InitializeComponent();

    imageListView1.Columns.Add(ColumnType.Name);
    imageListView1.Columns.Add(ColumnType.Dimensions);
    imageListView1.Columns.Add(ColumnType.FileSize);
    imageListView1.Columns.Add(ColumnType.FolderName);
    imageListView1.Columns.Add(ColumnType.DateModified);

    // set the custom grouper
    imageListView1.Columns[0].Grouper = new CustomGrouper();
}
```
In the `CustomGrouper` you need to supply both a group name and a hash code, because sometimes you want a different group name than the column text, for example when grouping by modified date, you may want to display group names as  `Last Week`, `Last Month`, `Older`, etc. instead of the date string.

**Comment by eXclusif20** [comment]
Once again thank you for your help.
I managed to convert the C # code to VB, and it was not easy for me.

Grouping by filepath works great.

![capture20200327100817175](https://user-images.githubusercontent.com/62645153/77741105-a0580000-7014-11ea-9eef-89340cc99b52.png)

![capture20200327100825842](https://user-images.githubusercontent.com/62645153/77741297-f167f400-7014-11ea-9b90-f2121bec57c4.png)

On the other hand concerning the grouping by type of file, I meet an unhandled error if I make the grouping before the list is completely loaded. If I wait for the complete loading of the list, the exception is not thrown and the grouping works.
I don't understand why because the code is strictly the same as for the filepath.

![capture20200327100847652](https://user-images.githubusercontent.com/62645153/77741226-d7c6ac80-7014-11ea-8c0e-87fa8a5f3aab.png)

![capture20200327100901940](https://user-images.githubusercontent.com/62645153/77741245-de552400-7014-11ea-850c-167f7a4adcce.png)

![capture20200327101053556](https://user-images.githubusercontent.com/62645153/77741197-c8476380-7014-11ea-9e98-3557fb33a11b.png)

Also, how do I get the ascending sort on the name of the groups? It may be simple, but I can't do it and I can't figure out why.

Do you have any idea what I'm doing wrong?

thank you so much

**Comment by oozcitak** [comment]
I found a bug in file type retrieval code and fixed it. I also added a new event which will be fired after file types are retrieved by the control. So please upgrade `ImageListView` to version `13.8.2` before proceeding.

> On the other hand concerning the grouping by type of file, I meet an unhandled error if I make the grouping before the list is completely loaded.

This happens because file type is loaded by a background thread. You need to account for FileType being `null` because the background thread has not yet processed the item:

```vb
Private Class FileTypeGrouper
    Implements ImageListView.IGrouper

    Public Function GetGroupInfo(item As ImageListViewItem) As ImageListView.GroupInfo Implements ImageListView.IGrouper.GetGroupInfo
        Dim str = item.GetSubItemText(ColumnType.FileType)
        If str Is Nothing Then
            ' item is not yet processed by the background thread
            ' group it under the "Unknown" group, we will fix that later
            ' also return a large hash code so that the "Unknown" group is 
            ' displayed at the bottom of other groups
            Return New ImageListView.GroupInfo("Unknown", Integer.MaxValue)
        Else
            Return New ImageListView.GroupInfo(str, str.GetHashCode())
        End If
    End Function
End Class
```
You also need to listen to the `ShellInfoCached` which was added with version `13.8.2` and use it to re-group the items:
```vb
Private Sub imageListView1_ShellInfoCached(sender As Object, e As ShellInfoCachedEventArgs)
    ' this event is fired when a file type's shell info is cached
    ' we re-sort items, so that groups are updated by our FileTypeGrouper
    ' after that some of the items in the "Unknown" group above will be assigned the proper group
    imageListView1.Sort()
End Sub
```
I prepared a demo project for you: [ILV_GroupingDemo.zip](https://github.com/oozcitak/imagelistview/files/4394121/ILV_GroupingDemo.zip)
