### ISSUE TITLE
Need to know scroll position while scrolling for Infinite scrolling

### ISSUE THREAD

**Issue by Omid3d** [oozcitak/imagelistview#225]
Hi first thank you so much for this great control. 
I used ImageListView to show images from web and it works great.

And now I need to implement infinite scroll behavior in my app. Normally to implement infinite scroll we should download a dedicated number of items from web at initial load time and then by each scroll to end (by user), we request more web items. 
To implement this, I need to know when vertical scroll bar reaches to the bottom and then fetch more items from web. I know this control has a built in virtual item loading mechanism but I cannot load all items from web (say 3000 items) to cache in control. And there is no scroll event or vScroll object to detect scroll position.

Do you have any idea how should I detect scroll position?

**Comment by oozcitak** [comment]
You could insert a dummy item at the end. When this item becomes visible you could remove the dummy and load the next batch. İnsert the dummy again...

**Comment by Omid3d** [comment]
Thank you for reply.
I know we can insert dummy item. But how should I know when user scrolled to the end to add this dummy item? I need something like scroll event to know scroll position at end.

**Comment by Omid3d** [comment]
> 
> 
> You could insert a dummy item at the end. When this item becomes visible you could remove the dummy and load the next batch. İnsert the dummy again...

**Comment by Omid3d** [comment]
> 
> 
> You could insert a dummy item at the end. When this item becomes visible you could remove the dummy and load the next batch. İnsert the dummy again...

Now is there any event or built in way in ImageListView to know when a specific item becomes visible?
Thank you for fast reply

**Comment by oozcitak** [comment]
> Now is there any event or built in way in ImageListView to know when a specific item becomes visible?
Thank you for fast reply

No there is no built-in event for this. But it would be possible to add it. The layout manager control keeps track of visible items. See: https://github.com/oozcitak/imagelistview/blob/789bca83c1220982ca01441b39b26b8d07c82d5b/ImageListView/ImageListViewLayoutManager.cs#L609

I currently don't have the time to work on `ImageListView` but if you are willing to send a pull request, I will try my best to integrate it quickly.

**Comment by oozcitak** [comment]
For a quick workaround you can check the `IsItemVisible` method of the control. May be poll it in intervals with a timer?

**Comment by Omid3d** [comment]
> For a quick workaround you can check the `IsItemVisible` method of the control. May be poll it in intervals with a timer?

Alright, thank you. 
Like you also I have few free time and I need some more time to check this.
 I will try your recommendation and share my results.
Again than you for help.

**Comment by Omid3d** [comment]
Hi 
Thank you for your support.
I decided to find an easy solution to my problem instead of working on your code.
I realized that VScrollBar member in ImageListView class is already available as a sub control. So I just subscribed to Scroll event of VScrollBar and some keyboard and mouse events to get desired result. For convenience I created a subclass of ImageListView and added this functionality to get scroll position when changed and by checking the ScrollMaximumPosition value in that event I can realize when to fetch more items from web:
```c#
public class ScrollAwareImageListView: ImageListView
    {
        protected int _lastScrollPosition = -1;
        protected VScrollBar _vscrollBarControl;

        public ScrollAwareImageListView ( ) : base ()
        {
            _vscrollBarControl = Controls.OfType<VScrollBar> ().SingleOrDefault ();
            _vscrollBarControl.Scroll += _vscrollBarControl_Scroll;
            _vscrollBarControl.MouseWheel += _vscrollBarControl_MouseWheel;
            _vscrollBarControl.KeyDown += _vscrollBarControl_KeyDown;
        }

        public int ScrollLastPosition { get; set; }

        public event EventHandler<ScrollEventArgs> Scroll;

        protected override void OnMouseWheel ( MouseEventArgs e )
        {
            base.OnMouseWheel (e);

            FireScrollEvent (new ScrollEventArgs (ScrollEventType.ThumbPosition, _lastScrollPosition, _vscrollBarControl.Value, ScrollOrientation.VerticalScroll));
            _lastScrollPosition = _vscrollBarControl.Value;
        }

        protected override void OnKeyDown ( KeyEventArgs e )
        {
            base.OnKeyDown (e);

            if (e.KeyCode == Keys.Down || e.KeyCode == Keys.PageDown || e.KeyCode == Keys.End || e.KeyCode == Keys.Up || e.KeyCode == Keys.PageUp || e.KeyCode == Keys.Home || e.KeyCode == Keys.Right || e.KeyCode == Keys.Left)
            {
                FireScrollEvent (new ScrollEventArgs (ScrollEventType.ThumbPosition, _lastScrollPosition, _vscrollBarControl.Value, ScrollOrientation.VerticalScroll));
                _lastScrollPosition = _vscrollBarControl.Value;
            }
        }

        protected void FireScrollEvent ( ScrollEventArgs e )
        {
            ScrollLastPosition = _vscrollBarControl.Maximum - _vscrollBarControl.LargeChange;
            Scroll?.Invoke (this, e);
        }

        private void _vscrollBarControl_KeyDown ( object sender, KeyEventArgs e )
        {
            if (e.KeyCode == Keys.Down || e.KeyCode == Keys.PageDown || e.KeyCode == Keys.End || e.KeyCode == Keys.Up || e.KeyCode == Keys.PageUp || e.KeyCode == Keys.Home || e.KeyCode == Keys.Right || e.KeyCode == Keys.Left)
            {
                FireScrollEvent (new ScrollEventArgs (ScrollEventType.ThumbPosition, _lastScrollPosition, _vscrollBarControl.Value, ScrollOrientation.VerticalScroll));
                _lastScrollPosition = _vscrollBarControl.Value;
            }
        }

        private void _vscrollBarControl_MouseWheel ( object sender, MouseEventArgs e )
        {
            FireScrollEvent (new ScrollEventArgs (ScrollEventType.ThumbPosition, _lastScrollPosition, _vscrollBarControl.Value, ScrollOrientation.VerticalScroll));
            _lastScrollPosition = _vscrollBarControl.Value;
        }

        private void _vscrollBarControl_Scroll ( object sender, ScrollEventArgs e )
        {
            FireScrollEvent (e);
        }

        protected override void Dispose ( bool disposing )
        {
            if (disposing)
            {
                // Events
                _vscrollBarControl.Scroll -= _vscrollBarControl_Scroll;
                _vscrollBarControl.MouseWheel -= _vscrollBarControl_MouseWheel;
                _vscrollBarControl.KeyDown -= _vscrollBarControl_KeyDown;
            }
        }
    }

```
For now this is just a workaround solution and I hope you or someone adds this functionality as a built in feature for this great control.
Thank you for your support.
